In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("b2b_directory_data.csv")

In [3]:
df

,Company Name,Website URL,Contact Number,Location/Address,Industry/Category,Company Description,Email Address
0,Geeks On Site,NaN,NaN,NaN,IT Services,NaN,NaN
1,AAA All Voice And Data Inc.,NaN,NaN,NaN,IT Services,NaN,NaN
2,My Computer Works,NaN,(800) 262-2219,NaN,IT Services,Nice support from their office thanks for ever...,NaN
3,Geeks On Site,NaN,(800) 531-2349,NaN,IT Services,"From Business: If you are in a crunch, Geeks o...",NaN
4,My Computer Works,NaN,(877) 201-0623,NaN,IT Services,From Business: Our professional and polite U.S...,NaN
...,...,...,...,...,...,...,...
87,Cybercity,https://www.cybercity.nyc,(212) 633-0649,"224 W 30th StNew York, NY 10001",IT Services,Avoid them. Our server crashed while we were ...,NaN
88,Global Data Publications Inc,https://www.globaldata.com/contact-us,(646) 395-5460,"441 Lexington AveNew York, NY 10017",IT Services,I found this company on Craigslist advertising...,NaN
89,New York Computer Help - SOHO,https://www.newyorkcomputerhelp.com,(212) 599-0339,"110 Greene St Fl 11New York, NY 10012",IT Services,"From Business: Founded in 2000, our computer s...",NaN
90,Promethean IT,NaN,(212) 226-6686,"65 Bleecker StNew York, NY 10012",IT Services,From Business: The ancient myth of Prometheus ...,NaN
91,Tech Support 4 NYC,http://www.techsupport4nyc.com,(877) 467-4989,"900 Avenue Of The AmericasNew York, NY 10011",IT Services,From Business: Computer Consulting firm servic...,NaN

In [4]:
df.columns

Index(['Company Name', 'Website URL', 'Contact Number', 'Location/Address',
       'Industry/Category', 'Company Description', 'Email Address'],
      dtype='object')

In [5]:
df.head()

,Company Name,Website URL,Contact Number,Location/Address,Industry/Category,Company Description,Email Address
0,Geeks On Site,NaN,NaN,NaN,IT Services,NaN,NaN
1,AAA All Voice And Data Inc.,NaN,NaN,NaN,IT Services,NaN,NaN
2,My Computer Works,NaN,(800) 262-2219,NaN,IT Services,Nice support from their office thanks for ever...,NaN
3,Geeks On Site,NaN,(800) 531-2349,NaN,IT Services,"From Business: If you are in a crunch, Geeks o...",NaN
4,My Computer Works,NaN,(877) 201-0623,NaN,IT Services,From Business: Our professional and polite U.S...,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Company Name         92 non-null     object
 1   Website URL          55 non-null     object
 2   Contact Number       90 non-null     object
 3   Location/Address     86 non-null     object
 4   Industry/Category    92 non-null     object
 5   Company Description  62 non-null     object
 6   Email Address        0 non-null      float64
dtypes: float64(1), object(6)
memory usage: 5.2+ KB

In [7]:
df.shape

(92, 7)

In [10]:
df.isna().sum()

Company Name            0
Website URL            37
Contact Number          2
Location/Address        6
Industry/Category       0
Company Description    30
Email Address          92
dtype: int64

In [11]:
# In email address all vaues are empty. so we are delete this columns

df=df.drop(columns=['Email Address'])

In [12]:
df

,Company Name,Website URL,Contact Number,Location/Address,Industry/Category,Company Description
0,Geeks On Site,NaN,NaN,NaN,IT Services,NaN
1,AAA All Voice And Data Inc.,NaN,NaN,NaN,IT Services,NaN
2,My Computer Works,NaN,(800) 262-2219,NaN,IT Services,Nice support from their office thanks for ever...
3,Geeks On Site,NaN,(800) 531-2349,NaN,IT Services,"From Business: If you are in a crunch, Geeks o..."
4,My Computer Works,NaN,(877) 201-0623,NaN,IT Services,From Business: Our professional and polite U.S...
...,...,...,...,...,...,...
87,Cybercity,https://www.cybercity.nyc,(212) 633-0649,"224 W 30th StNew York, NY 10001",IT Services,Avoid them. Our server crashed while we were ...
88,Global Data Publications Inc,https://www.globaldata.com/contact-us,(646) 395-5460,"441 Lexington AveNew York, NY 10017",IT Services,I found this company on Craigslist advertising...
89,New York Computer Help - SOHO,https://www.newyorkcomputerhelp.com,(212) 599-0339,"110 Greene St Fl 11New York, NY 10012",IT Services,"From Business: Founded in 2000, our computer s..."
90,Promethean IT,NaN,(212) 226-6686,"65 Bleecker StNew York, NY 10012",IT Services,From Business: The ancient myth of Prometheus ...
91,Tech Support 4 NYC,http://www.techsupport4nyc.com,(877) 467-4989,"900 Avenue Of The AmericasNew York, NY 10011",IT Services,From Business: Computer Consulting firm servic...

In [13]:
df.isna().sum()

Company Name            0
Website URL            37
Contact Number          2
Location/Address        6
Industry/Category       0
Company Description    30
dtype: int64

In [14]:
# now handle missing values 
#Drop rows with missing 'Contact Number' (assuming it's essential)

df = df.dropna(subset=['Contact Number'])

In [16]:
df.isna().sum()

Company Name            0
Website URL            35
Contact Number          0
Location/Address        4
Industry/Category       0
Company Description    28
dtype: int64

In [19]:
import warnings

warnings.filterwarnings('ignore')

In [20]:
 # Fill missing values in 'Website URL' and 'Location/Address' with placeholders
df['Website URL'].fillna('Not Available', inplace=True)
df['Location/Address'].fillna('Not Provided', inplace=True)

In [21]:
df.isna().sum()

Company Name            0
Website URL             0
Contact Number          0
Location/Address        0
Industry/Category       0
Company Description    28
dtype: int64

In [23]:
#fill missing values in 'Company Description' with a placeholder

df['Company Description'].fillna('Description Not Available', inplace=True)

In [24]:
df.isna().sum()

Company Name           0
Website URL            0
Contact Number         0
Location/Address       0
Industry/Category      0
Company Description    0
dtype: int64

In [25]:
df

,Company Name,Website URL,Contact Number,Location/Address,Industry/Category,Company Description
2,My Computer Works,Not Available,(800) 262-2219,Not Provided,IT Services,Nice support from their office thanks for ever...
3,Geeks On Site,Not Available,(800) 531-2349,Not Provided,IT Services,"From Business: If you are in a crunch, Geeks o..."
4,My Computer Works,Not Available,(877) 201-0623,Not Provided,IT Services,From Business: Our professional and polite U.S...
5,Geeks on Site,Not Available,(877) 223-4607,Not Provided,IT Services,From Business: With over 20 years of experienc...
6,AAA All Voice And Data Inc.,https://api.superpages.com/xml/search?SRC=ypin...,(646) 921-7849,"303 Avenue P Apt F7Brooklyn, NY 11204",IT Services,Guys from AAA did great installation for us. ...
...,...,...,...,...,...,...
87,Cybercity,https://www.cybercity.nyc,(212) 633-0649,"224 W 30th StNew York, NY 10001",IT Services,Avoid them. Our server crashed while we were ...
88,Global Data Publications Inc,https://www.globaldata.com/contact-us,(646) 395-5460,"441 Lexington AveNew York, NY 10017",IT Services,I found this company on Craigslist advertising...
89,New York Computer Help - SOHO,https://www.newyorkcomputerhelp.com,(212) 599-0339,"110 Greene St Fl 11New York, NY 10012",IT Services,"From Business: Founded in 2000, our computer s..."
90,Promethean IT,Not Available,(212) 226-6686,"65 Bleecker StNew York, NY 10012",IT Services,From Business: The ancient myth of Prometheus ...
91,Tech Support 4 NYC,http://www.techsupport4nyc.com,(877) 467-4989,"900 Avenue Of The AmericasNew York, NY 10011",IT Services,From Business: Computer Consulting firm servic...

,Company Name,Website URL,Contact Number,Location/Address,Industry/Category,Company Description
2,My Computer Works,Not Available,(800) 262-2219,Not Provided,IT Services,Nice support from their office thanks for ever...
3,Geeks On Site,Not Available,(800) 531-2349,Not Provided,IT Services,"From Business: If you are in a crunch, Geeks o..."
4,My Computer Works,Not Available,(877) 201-0623,Not Provided,IT Services,From Business: Our professional and polite U.S...
5,Geeks on Site,Not Available,(877) 223-4607,Not Provided,IT Services,From Business: With over 20 years of experienc...
6,AAA All Voice And Data Inc.,https://api.superpages.com/xml/search?SRC=ypin...,(646) 921-7849,"303 Avenue P Apt F7Brooklyn, NY 11204",IT Services,Guys from AAA did great installation for us. ...
...,...,...,...,...,...,...
87,Cybercity,https://www.cybercity.nyc,(212) 633-0649,"224 W 30th StNew York, NY 10001",IT Services,Avoid them. Our server crashed while we were ...
88,Global Data Publications Inc,https://www.globaldata.com/contact-us,(646) 395-5460,"441 Lexington AveNew York, NY 10017",IT Services,I found this company on Craigslist advertising...
89,New York Computer Help - SOHO,https://www.newyorkcomputerhelp.com,(212) 599-0339,"110 Greene St Fl 11New York, NY 10012",IT Services,"From Business: Founded in 2000, our computer s..."
90,Promethean IT,Not Available,(212) 226-6686,"65 Bleecker StNew York, NY 10012",IT Services,From Business: The ancient myth of Prometheus ...
91,Tech Support 4 NYC,http://www.techsupport4nyc.com,(877) 467-4989,"900 Avenue Of The AmericasNew York, NY 10011",IT Services,From Business: Computer Consulting firm servic...

In [29]:
df.duplicated().sum()

np.int64(0)